export const BODY_REGIONS = [
  { id: 'head_front', label: 'Head (Front)', view: 'front' as const },
  { id: 'face', label: 'Face', view: 'front' as const },
  { id: 'neck_front', label: 'Neck', view: 'front' as const },
  { id: 'left_shoulder', label: 'Left Shoulder', view: 'both' as const },
  { id: 'right_shoulder', label: 'Right Shoulder', view: 'both' as const },
  { id: 'chest', label: 'Chest', view: 'front' as const },
  { id: 'left_upper_arm', label: 'Left Upper Arm', view: 'both' as const },
  { id: 'right_upper_arm', label: 'Right Upper Arm', view: 'both' as const },
  { id: 'left_elbow', label: 'Left Elbow', view: 'both' as const },
  { id: 'right_elbow', label: 'Right Elbow', view: 'both' as const },
  { id: 'abdomen', label: 'Abdomen', view: 'front' as const },
  { id: 'left_forearm', label: 'Left Forearm', view: 'both' as const },
  { id: 'right_forearm', label: 'Right Forearm', view: 'both' as const },
  { id: 'left_wrist', label: 'Left Wrist', view: 'both' as const },
  { id: 'right_wrist', label: 'Right Wrist', view: 'both' as const },
  { id: 'left_hand', label: 'Left Hand', view: 'both' as const },
  { id: 'right_hand', label: 'Right Hand', view: 'both' as const },
  { id: 'hip_pelvis', label: 'Hip/Pelvis', view: 'front' as const },
  { id: 'left_upper_leg', label: 'Left Upper Leg', view: 'both' as const },
  { id: 'right_upper_leg', label: 'Right Upper Leg', view: 'both' as const },
  { id: 'left_knee', label: 'Left Knee', view: 'both' as const },
  { id: 'right_knee', label: 'Right Knee', view: 'both' as const },
  { id: 'left_lower_leg', label: 'Left Lower Leg', view: 'both' as const },
  { id: 'right_lower_leg', label: 'Right Lower Leg', view: 'both' as const },
  { id: 'left_ankle', label: 'Left Ankle', view: 'both' as const },
  { id: 'right_ankle', label: 'Right Ankle', view: 'both' as const },
  { id: 'left_foot', label: 'Left Foot', view: 'both' as const },
  { id: 'right_foot', label: 'Right Foot', view: 'both' as const },
  { id: 'head_back', label: 'Head (Back)', view: 'back' as const },
  { id: 'neck_back', label: 'Neck (Back)', view: 'back' as const },
  { id: 'upper_back', label: 'Upper Back', view: 'back' as const },
  { id: 'lower_back', label: 'Lower Back', view: 'back' as const },
] as const

export type BodyRegionId = typeof BODY_REGIONS[number]['id']
