import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

/**
 * Generate a branded PDF report with a header, data table, and footer.
 *
 * @param title       - Report title (e.g. "Reading History")
 * @param facilityName - Facility name for the header
 * @param dateRange   - Human-readable date range string (e.g. "Jun 1 - Jun 14, 2025")
 * @param columns     - Column header labels
 * @param data        - 2D array of string cell values
 * @returns ArrayBuffer containing the PDF bytes
 */
export function generatePdfReport(
  title: string,
  facilityName: string,
  dateRange: string,
  columns: string[],
  data: string[][]
): ArrayBuffer {
  const doc = new jsPDF()

  // --- Header band ---
  doc.setFillColor(0, 34, 68) // Navy (#002244)
  doc.rect(0, 0, 210, 25, "F")

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.text(facilityName, 14, 12)

  doc.setFontSize(10)
  doc.text(`${title}  |  ${dateRange}`, 14, 20)

  // --- Data table ---
  doc.setTextColor(0, 0, 0)
  autoTable(doc, {
    head: [columns],
    body: data,
    startY: 30,
    headStyles: {
      fillColor: [0, 34, 68],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  })

  // --- Footer on every page ---
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(120, 120, 120)
    doc.text(
      "Generated by Max Facility Rink Reports",
      14,
      doc.internal.pageSize.height - 10
    )
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 30,
      doc.internal.pageSize.height - 10
    )
  }

  return doc.output("arraybuffer")
}
