import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface ReportColumn {
  key: string
  label: string
  width?: number
}

export interface PdfReportConfig {
  title: string
  facilityName: string
  dateRange: { start: string; end: string }
  columns: ReportColumn[]
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data: Record<string, any>[]
}

// Brand color constants (RGB tuples for jsPDF)
const NAVY: [number, number, number] = [0, 34, 68] // #002244
const WHITE: [number, number, number] = [255, 255, 255]
const WOLF_GREY_LIGHT: [number, number, number] = [209, 213, 216] // #D1D5D8
const WOLF_GREY_DARK: [number, number, number] = [107, 114, 128] // #6B7280

export function generatePdfReport(config: PdfReportConfig): Uint8Array {
  const { title, facilityName, dateRange, columns, data } = config
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // ── Header: Navy background bar ──
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, pageWidth, 28, 'F')

  // "Max Facility" brand text
  doc.setTextColor(...WHITE)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('Max Facility', 14, 13)

  // Facility name
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(facilityName, 14, 22)

  // ── Report title ──
  doc.setTextColor(...NAVY)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(title, pageWidth / 2, 40, { align: 'center' })

  // ── Date range ──
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...WOLF_GREY_DARK)
  doc.text(
    `${dateRange.start} - ${dateRange.end}`,
    pageWidth / 2,
    48,
    { align: 'center' }
  )

  // ── Data table ──
  const head = [columns.map((col) => col.label)]
  const body = data.map((row) =>
    columns.map((col) => {
      const value = row[col.key]
      if (value === null || value === undefined) return ''
      return String(value)
    })
  )

  const columnWidths: Record<number, { cellWidth: number }> = {}
  columns.forEach((col, i) => {
    if (col.width) {
      columnWidths[i] = { cellWidth: col.width }
    }
  })

  autoTable(doc, {
    startY: 54,
    head,
    body,
    theme: 'striped',
    headStyles: {
      fillColor: NAVY,
      textColor: WHITE,
      fontStyle: 'bold',
      fontSize: 9,
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 30, 30],
    },
    alternateRowStyles: {
      fillColor: WOLF_GREY_LIGHT,
    },
    columnStyles: columnWidths,
    margin: { left: 14, right: 14 },
    styles: {
      cellPadding: 3,
      overflow: 'linebreak',
    },
    didDrawPage: (hookData) => {
      // ── Footer on every page ──
      const pageHeight = doc.internal.pageSize.getHeight()
      const pageNumber = doc.getNumberOfPages()
      const currentPage = hookData.pageNumber

      // Divider line
      doc.setDrawColor(...WOLF_GREY_LIGHT)
      doc.setLineWidth(0.5)
      doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16)

      // Footer text
      doc.setFontSize(7)
      doc.setTextColor(...WOLF_GREY_DARK)
      doc.setFont('helvetica', 'normal')
      doc.text(
        'Generated by Max Facility Rink Reports',
        14,
        pageHeight - 10
      )

      // Generated date
      const generatedDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
      doc.text(generatedDate, pageWidth / 2, pageHeight - 10, {
        align: 'center',
      })

      // Page numbers
      doc.text(
        `Page ${currentPage} of ${pageNumber}`,
        pageWidth - 14,
        pageHeight - 10,
        { align: 'right' }
      )
    },
  })

  // Fix page count on all pages (jsPDF renders total pages after all pages are drawn)
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    const pageHeight = doc.internal.pageSize.getHeight()
    // Overwrite the page number area with correct total
    doc.setFillColor(255, 255, 255)
    doc.rect(pageWidth - 60, pageHeight - 14, 50, 8, 'F')
    doc.setFontSize(7)
    doc.setTextColor(...WOLF_GREY_DARK)
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 14,
      pageHeight - 10,
      { align: 'right' }
    )
  }

  const arrayBuffer = doc.output('arraybuffer')
  return new Uint8Array(arrayBuffer)
}
