import { Resend } from 'resend'

let resendInstance: Resend | null = null

function getResend(): Resend | null {
  if (!process.env.RESEND_API_KEY) {
    return null
  }
  if (!resendInstance) {
    resendInstance = new Resend(process.env.RESEND_API_KEY)
  }
  return resendInstance
}

export async function sendEmailNotification(
  recipientEmail: string,
  title: string,
  body: string,
  link?: string
): Promise<{ success: boolean }> {
  const resend = getResend()

  if (!resend) {
    console.log(
      `[Email] Dev mode — To: ${recipientEmail}, Subject: ${title}, Body: ${body}${link ? `, Link: ${link}` : ''}`
    )
    return { success: true }
  }

  try {
    await resend.emails.send({
      from: 'Max Facility <notifications@maxfacility.com>',
      to: recipientEmail,
      subject: title,
      html: buildEmailHtml(title, body, link),
    })
    return { success: true }
  } catch (error) {
    console.error('[Email] Send error:', error)
    return { success: false }
  }
}

function buildEmailHtml(title: string, body: string, link?: string): string {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://app.maxfacility.com'
  const fullLink = link ? `${appUrl}${link.startsWith('/') ? link : `/${link}`}` : null

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color: #f4f4f5;">
    <tr>
      <td align="center" style="padding: 40px 16px;">
        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width: 560px; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

          <!-- Header -->
          <tr>
            <td style="background-color: #002244; padding: 24px 32px; text-align: center;">
              <h1 style="margin: 0; font-size: 20px; font-weight: 700; color: #ffffff; letter-spacing: 0.5px;">
                Max Facility
              </h1>
            </td>
          </tr>

          <!-- Content -->
          <tr>
            <td style="padding: 32px;">
              <h2 style="margin: 0 0 12px; font-size: 18px; font-weight: 600; color: #002244;">
                ${escapeHtml(title)}
              </h2>
              <p style="margin: 0 0 24px; font-size: 15px; line-height: 1.6; color: #4b5563;">
                ${escapeHtml(body)}
              </p>
              ${
                fullLink
                  ? `<table role="presentation" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td style="border-radius: 8px; background-color: #69BE28;">
                    <a href="${escapeHtml(fullLink)}" target="_blank" rel="noopener noreferrer" style="display: inline-block; padding: 12px 28px; font-size: 14px; font-weight: 600; color: #ffffff; text-decoration: none;">
                      View Details
                    </a>
                  </td>
                </tr>
              </table>`
                  : ''
              }
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding: 0 32px;">
              <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 0;" />
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 20px 32px 24px; text-align: center;">
              <p style="margin: 0; font-size: 12px; color: #9ca3af;">
                Generated by Max Facility Rink Reports
              </p>
              <p style="margin: 4px 0 0; font-size: 12px; color: #9ca3af;">
                <a href="${escapeHtml(appUrl)}" style="color: #69BE28; text-decoration: none;">maxfacility.com</a>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
